donation/urls.py
from django.urls import path, include
from donation import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('money',views.testdonatemoney)
router.register('user', views.CurrentUserViewSet)
router.register('orphanage',views.testorphanage)


app_name = 'donation'

urlpatterns = [
    path('test/',include(router.urls)),
    path('api/',views.rest_moneyview,name='rest'),
    path('donate_money/',views.donatemoneyview,name='donatemoney'),
    path('donate_valuables/',views.donatevaluablesview,name='donate_valuables'),
    path('donation_done/',views.donation_completedview,name='completed'),
    path('donation_interrupt/',views.donation_interruptview,name='cancel'),
    path('requestplaced/',views.donation_completedview,name='request_placed'),
    path('paypal_home/<int:tid>/<int:amount>/<str:orphanage_id1>/',views.paypal_home,name='inprogress'),
    path('paypal_return/',views.paypal_return),
    path('paypal_cancel/',views.paypal_cancel),
#    path('facebook/',views.facebookview,name='facebook'),
    path('social/',views.socialview,name='social'),
    path('Accepted/',views.acceptedview,name='accepted'),
    path('Rejected/',views.rejectedview,name='rejected'),
    path('history/',views.historyview,name='history'),
    path('received/',views.receivedview,name='received'),

]

oms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from homepage.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    path('homepage/',include('homepage.urls')),
    path('registration/',include('registration.urls')),
    path('orphanage_dashboard/', include('orphanageadmin.urls')),
    path('superuser/', include('superuser.urls')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('userdashboard/',include('userdashboard.urls')),
    path('donation/',include('donation.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') ,
            name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from registration.form import CustomAuthForm

app_name = 'registration'
urlpatterns = [
    path('', views.index, name='profile'),
    # path('donate_history', views.index1, name='donate_history'),
    # path('join_orphan', views.index2, name='join_orphan'),
    # path('near_you', views.index3, name='near_you'),
    # path('pending', views.index4, name='pending'),

    path('login', views.login_view, name='login'),
    path('register', views.signup, name='signup'),
    path(r'getData/<slug:user_type>/', views.get_data, name='get_data'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
         name='activate'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('logout/', views.logout_view, name= 'logout'),
    path('solution',views.solution,name='solution'),
    path('result',views.result,name='r_result1'),



    # path(r'password_reset/', auth_views.PasswordResetView.as_view() , name= 'password_reset'),
    # path(r'password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name= 'password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #
    # path(r'reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_engine='registration/password_reset_confirm.html'), name= 'password_reset_complete'),




    # path('register', views.orphanage_signup, name='orphanage_signup'),
    # path('login_result', views.loginstatus, name='loginstatus'),
    # path('login12', views.login12, name='login12'),
    # path('login1', views.login1, name='login1'),
    # path('signup1/user', views.user_signup1, name='user_signup1'),
    # path('signup12/user', views.user_signup12, name='user_signup12'),
    # path('signup1/orphanage', views.orphanage_signup1, name='orphanage_signup1'),
    # path('signup12/orphanage', views.orphanage_signup12, name='orphanage_signup12'),

]

userdashboard/urls.py
from django.urls import path
from . import views
app_name = 'userdashboard'

urlpatterns = [
path('Profile',views.Profile,name='u_Profile'),
path('result1',views.profileupdate,name='u_result11'),
path('result12', views.editprofile, name='u_result12'),
path('requestJoinOrphan', views.requestJoinOrphan, name = "request_joinorphan"),
path('acceptedJoinOrphanReqs', views.acceptedJoinOrphan_requests, name= "accepted_joinorphan"),
path('rejectedJoinOrphanReqs', views.rejectedJoinOrphan_requests, name= "rejected_joinorphan"),
path('pendingJoinOrphanReqs', views.pendingJoinOrphan_requests, name= "pending_joinorphan")
]

donation/models.py
from django.db import models
from paypal.standard.ipn.signals import valid_ipn_received, invalid_ipn_received

def show_me_the_money(sender, **kwargs):
    print("MAY be")

# Create your models here.
print("will it work")
valid_ipn_received.connect(show_me_the_money)

donation/forms.py
from django import forms
from django.db import models

# Create your forms here.

class donatemoneyform(forms.Form):
    tid = forms.IntegerField()
    user_name = forms.CharField()
    transfer = forms.CharField()
    amount = forms.IntegerField()
    date_of_donation = forms.DateTimeField()
    description = forms.CharField()
    orphanage = forms.CharField()

class donatevaluablesform(forms.Form):
    tid = forms.IntegerField()
    user_name = forms.CharField()
    uid = forms.IntegerField()
    type = forms.CharField()
    weight = forms.IntegerField()
    length = forms.IntegerField()
    width = forms.IntegerField()
    height = forms.IntegerField()

donation/views.py
from django.shortcuts import render
import json
import requests
from json import load
from urllib.request import urlopen
from django.shortcuts import render
from django.db import connection
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received, invalid_ipn_received
from homepage.models import donatemoney,donatevaluables,Orphanage,Transport
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status,viewsets
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from .serializers import MoneySerializer,testdonatemoneyserializer,testorphanageserializer,CurrentUserSerializer
import random
import pdb

# Create your views here.

@csrf_exempt
def show_me_the_money(sender, **kwargs):
    ipn_obj = sender
    print(ipn_obj)
    print("may be")
    if ipn_obj.payment_status == ST_PP_COMPLETED:
        # Undertake some action depending upon `ipn_obj`.
        if ipn_obj.custom == "Upgrade all users!":
            Users.objects.update(paid=True)
    else:
        Users.objects.update(paid=False)



# Create your views here.
@login_required(login_url='registration:login')
def donatemoneyview(request):
    Orphanages = Orphanage.objects.all()
    if request.method =='POST':
        user_id = request.user
        transfer = request.POST['transfer']
        amount = request.POST['amount']
        orphanage_id1 = request.POST['orphanage_id']
        orphanage=Orphanage.objects.get(pk = orphanage_id1)
        orphanage_name = orphanage.orphanage_name
        print(orphanage_id1)
        description= request.POST['description']
        status = "0"
        saveform = donatemoney.objects.create(user_id=user_id,transfer=transfer,amount=amount,orphanage_id=orphanage,orphanage_name=orphanage_name,description=description,status=status)
        saveform.save()
        tid=donatemoney.objects.latest('pk')
        print(tid)
        tidstring=tid.pk
        if transfer=="paypal":
            return HttpResponseRedirect(reverse('donation:inprogress',args=(tidstring,amount,orphanage_id1))) 
    else:
        context = {
            'orphanages': Orphanages
        }
    return render(request,'donation/money.html',context)

@csrf_exempt
def donation_completedview(request):
    args = {'post':request.POST,'get':request.GET}
    data=donatemoney.objects.latest()
    data.status='1'
    valid_ipn_received.connect(show_me_the_money)
    data.save()
    return render(request,'donation/donation_done.html',args)

@csrf_exempt
def donation_interruptview(request):
    data=donatemoney.objects.latest()
    data.status='-1'
    data.save()
    return render(request,'donation/donation_interrupt.html')

@login_required(login_url='registration:login')
def donatevaluablesview(request):
    Orphanages = Orphanage.objects.all()
    
    if request.method =='POST':
        user_id = request.user
        type=request.POST.get('type')
        quantity=request.POST.get('quantity')
        orphanage_id1 = request.POST['orphanage_id']
        orphanage=Orphanage.objects.get(pk = orphanage_id1)
        orphanage_name = orphanage.orphanage_name
        object = request.POST.get('object_name')
        orphanage = Orphanage.objects.get(pk = orphanage_id1)
        description= request.POST.get('description')
        address = request.POST.get('address')
        print(user_id)
        status='0'
        saveform = donatevaluables.objects.create(user_id=user_id,donation_type=type,orphanage_name=orphanage_name,object_name=object,orphanage_id=orphanage,quantity=quantity,description=description,address=address,status=status)
        saveform.save()
        return HttpResponseRedirect(reverse('donation:request_placed'))
    else:
        context = {
            'orphanages': Orphanages
        }
        return render(request, 'donation/valuables.html',context)

def paypal_home(request,tid,amount,orphanage_id1): 
    selected_orphanage=Orphanage.objects.get(pk = orphanage_id1)
    orphanage=selected_orphanage.orphanage_name
    user_name=request.user
    account=selected_orphanage.account
    num = random.randint(1,100000)
    print(account)
    paypal_dict = {
        "business": account,
        "amount": amount,
        "currency-code":"USD",
        "item_name": num,
        "invoice": num,
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": "http://38ed8983.ngrok.io/donation/donation_done/",
        "cancel_return": "http://38ed8983.ngrok.io/donation/donation_interrupt/",
    }
    form = PayPalPaymentsForm(initial=paypal_dict)
    data=donatemoney.objects.latest()
    context = {"form": form,"data":data,"user_name":user_name,"orphanage":orphanage}
    return render(request, "donation/gatewaypage.php", context)

@csrf_exempt
def paypal_cancel(request):
    data=donatemoney.objects.latest()
    data.status='-1'
    data.save()
    return render(request,'donation/paypal_cancel.html')


#return url is mistake
@csrf_exempt
def paypal_return(request):
   data=donatemoney.objects.latest()
   data.status='1'
   valid_ipn_received.connect(show_me_the_money)
   data.save()
   return render(request,'donation/paypal_return.html')

def rejectedview(request):
    user = request.user
    rejected = donatevaluables.objects.filter(user_id=user,status=-2)
    
    context = {"rejected":rejected}
    return render(request, "donation/Rejected.html", context)


def receivedview(request):
    user = request.user
    received = donatevaluables.objects.filter(user_id=user,status=0)
    context = {"received": received}
    return render(request, "donation/received.html", context)

def acceptedview(request):
    user = request.user
    transport = Transport.objects.filter(status=0)
    accepted = donatevaluables.objects.filter(user_id=user,status=1)
    transpose=[]
    for accept in accepted:
        for trans in transport:
            if trans.danation_id == accept.pk:
                accept.status = 10
                break

    context = {"accepted": accepted,"transpose":transpose}
    return render(request, "donation/Accepted.html", context)


def historyview(request):
    user = request.user
    donations = donatemoney.objects.filter(user_id=user)
    
    context = {"donations": donations}
    return render(request, "donation/history.html", context)




#COULD not access 2d list in django
def socialview(request):
    url="https://graph.facebook.com/v5.0/107316914058945?fields=posts.limit(20)%7Bmessage%2Cfrom%2Cadmin_creator%2Clikes.limit(30)%2Cfull_picture%7D%2Cevents.limit(10)%7Bowner%2Cdescription%2Cstart_time%7D&access_token=EAALOtHuxZAWUBANT76cZC0rRVlFDrwXrReqBWC4jiotiZCZAI7KIp9Glc1yakdJ1rJG0V8mRxNYGiIaKlHbc3dIVXWzPUOImGjVp8kxAQb71p7d2t4Kk5W2LzIwEnrpfDUQbiN1vHH2gUJR9QLmP9hBnLOsKZBDjYWFq7Dn6cc3ZAMLSVaXBZBRYlzSIuO9G6ZB4kevqTwh0DgZDZD"
    response=urlopen(url)
    json_text = load(response)
    
    feed_messages=list()
    feed_pictures=list()
    event_owner=list()
    event_description=list()
    event_start=list()
    
    feed = [[] for i in range(10)]
   

    for info in json_text["posts"]["data"]:
        mess=info.get('message', 'null')
        pics=info.get('full_picture','null')
        likes=info.get('likes','null')
        feed_messages.append(mess)
        feed_pictures.append(pics)
        
    for info in json_text["events"]["data"]:
        mess=info.get('description', 'null')
        owner=info.get('name', 'null')
        start=info.get('start_time','null')
        event_description.append(mess)
        event_owner.append(owner)
        event_start.append(pics)
        
    print(feed_messages)
    print(feed_pictures)

    for i in range(len(feed_messages)):
        print(feed_messages[i])
        feed[i][0]=feed_messages[i]
        feed[i][1]=feed_pictures[i]
    
    for i in range(len(event_description)):
        event[i][0]=event_description[i]
        event[i][1]=feed_pictures[i]
    
    context = {"feed":feed,"mess": feed_messages,"pics":feed_pictures,"desc":event_description,"owner":event_owner,"start":event_start}
    return render(request, "donation/social.html", context)
    
   
@api_view(['GET',])
def rest_moneyview(request):

    try:
        print("1")
        donations = donatemoney.objects.all()
    except donatemoney.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    serializer = MoneySerializer(donations)
    print(serializer)
    print(serializer.data)
    return Response(serializer.data)
#
    #queryset = donatemoney.objects.all()
    #serializer_class = MoneySerializer

class testdonatemoney(viewsets.ModelViewSet):
    queryset = donatemoney.objects.all()
    serializer_class= testdonatemoneyserializer


class CurrentUserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = CurrentUserSerializer
    
class testorphanage(viewsets.ModelViewSet):
    queryset = Orphanage.objects.all()
    serializer_class = testorphanageserializer


valid_ipn_received.connect(show_me_the_money)

templates/donation/Accepted.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-valuable")
</script>
    <h3>Accepted Transactions:</h3>
    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Transaction id</th>
      <th scope="col">Orphanage</th>
      <th scope="col">Type</th>
      <th scope="col">Object</th>
      <th scope="col">Date</th>
 <th scope="col">delivery</th>
    </tr>
  </thead>
  <tbody>
    
    {% for accept in accepted %}
      <tr>
      <th scope="row">{{accept.tid}}</th>
      <td>{{accept.orphanage_name}}</td>
      <td>{{accept.donation_type}}</td>
      <td>{{accept.object_name}}</td>
      <td>{{accept.date_of_donation}}</td>
      {% if accept.status == 10 %}
      <td> <form action="{% url 'registration:solution' %}" method="post" >
          {% csrf_token %}
        <input type="hidden" name='name' value="{{ accept.pk }}" >
        <button class="btn btn-primary "  >Accept</button>

        </form>
       </button></td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
            <!-- content ends here-->
{% endblock content %}

templates/donation/Rejected.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
    sidebar_shift("sidebar-valuable")
</script>



            <h3>Rejected Transactions:</h3>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Transaction id</th>
                        <th scope="col">Orphanage</th>
                        <th scope="col">Type</th>
                        <th scope="col">Object</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for reject in rejected %}
                    <tr>
                        <th scope="row">{{reject.tid}}</th>
                        <td>{{reject.orphanage_name}}</td>
                        <td>{{reject.donation_type}}</td>
                        <td>{{reject.object_name}}</td>
                        <td>{{reject.date_of_donation}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
       
    

<!-- content ends here-->
{% endblock content %}

templates/donation/donation_done.html
{{ post }}

{{ get }}

templates/donation/history.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
     <h3>Accepted Transactions:</h3>
    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Transaction id</th>
      <th scope="col">Orphanage</th>
      <th scope="col">Amount</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    {% for accept in donations %}
      <tr>
      <th scope="row">{{accept.tid}}</th>
      <td>{{accept.orphanage_name}}</td>
      <td>{{accept.amount}}</td>
      <td>{{accept.date_of_donation}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

templates/donation/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>

templates/donation/money.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-donate")
</script>
<script>
    var selected_options = document.querySelector('#drop').selectedOptions;

for(var i=0; i<selected_options.length; i++) {
	// echoes the text of the option
	console.log(selected_options[i].text);
	
	// echoes the value of the option
	console.log(selected_options[i].value);
}
</script>
    <div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v5.0&appId=790224518079845&autoLogAppEvents=1"></script>
    <form method="post" >
        {% csrf_token %}
        <div class="form-group">
           
                        <div class="card">
                <div class="card-header">
                    <h5 class="text-center text-heading title">Donate money</h5>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                        <div class="form-group">
                            <!-- <span>Subject</span> -->
                            <label for="drop">Orphanage</label>
                            <select class="btn btn-outline-info dropdown-toggle z-depth-0 border-bottom drop-btn" name="orphanage_id" id="drop">
                                <option value="" selected>Choose option</option>
                                {% for orphanage in orphanages %}
                                <option value="{{ orphanage.pk }}">{{ orphanage.orphanage_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <!--Message-->
                        <div class="md-form">
                            <textarea id="Message" name="description" class="form-control md-textarea" rows="2"></textarea>
                            <label for="Message">Message</label>
                        </div>
                         <div class="form-group">
                            <span class="mr-3">Payment gateway</span>
                            <!-- Default inline 1-->
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" class="custom-control-input" id="defaultInline1" value="paypal" name="transfer">
                                <label class="custom-control-label" for="defaultInline1">Paypal</label>
                            </div>

                        </div> 
                            <div class="md-form mt-3 ">
                            <label for="amount">Amount</label>
                            <input type="text" id="amount" name="amount" class="form-control" />   
                        </div>
                    </div>

                <div class="col-sm-8">
                <div class="md-form">
                           <button style="text-align:center" value="submit" type="submit" class="btn btn-primary waves-effect waves-light form-button">Submit</button>
                        
                    </div>
                </div>
                </div>
                </div>
                </div>
            
                </div>
            </div>

                                
</form>

            <!-- content ends here-->
{% endblock content %}

templates/donation/paypal_cancel.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
  <div class="modal fade" id="myModal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h3 style="text-align:center">Donation successful</h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
       </div>
<!-- Modal body -->
      <div class="modal-body">
        <h4 style="text-align:center">Share us with your friends</h4>
      
          
        </div>
        <div>
        <a href="{% url 'userdashboard:u_Profile' %}">Go to home</a>
          <div class="fb-share-button" data-href="http://127.0.0.1:8000/" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share us with your friends</a>
        </div>
        </div>
      </div>
    </div>
  </div>
  
</div>


<script>
$(document).ready(function(){
  // Show the Modal on load
  $("#myModal").modal("show");
    
  // Hide the Modal
  $("#myBtn").click(function(){
    $("#myModal").modal("hide");
  });
});
</script>

{% endblock content %}

templates/donation/paypal_return.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}


{{ post }}

{{ get }}
  <div class="modal fade" id="myModal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h3 style="text-align:center">Donation successful</h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
       </div>
<!-- Modal body -->
      <div class="modal-body">
        <h4 style="text-align:center">Share us with your friends</h4>
      
          
        </div>
        <div>
        <a href="{% url 'userdashboard:u_Profile' %}">Go to home</a>
          <div class="fb-share-button" data-href="http://127.0.0.1:8000/" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share us with your friends</a>
        </div>
        </div>
      </div>
    </div>
  </div>
  
</div>


<script>
$(document).ready(function(){
  // Show the Modal on load
  $("#myModal").modal("show");
    
  // Hide the Modal
  $("#myBtn").click(function(){
    $("#myModal").modal("hide");
  });
});
</script>

{% endblock content %}

templates/donation/received.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
    sidebar_shift("sidebar-valuable")
</script>
            <h3>Yet to be confirmed Transactions:</h3>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Transaction id</th>
                        <th scope="col">Orphanage</th>
                        <th scope="col">Type</th>
                        <th scope="col">Object</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for receive in received %}
                    <tr>
                        <th scope="row">{{receive.tid}}</th>
                        <td>{{receive.orphanage_name}}</td>
                        <td>{{receive.donation_type}}</td>
                        <td>{{receive.object_name}}</td>
                        <td>{{receive.date_of_donation}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
       
    

<!-- content ends here-->
{% endblock content %}

templates/donation/requestplaced.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
      <!-- The Modal -->
  <div class="modal fade" id="myModal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h3>Your request has been placed</h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
       </div>
<!-- Modal body -->
      <div class="modal-body">
        <h4 style="text-align:center">Share us with your friends</h4>
      
          
        </div>
        <a href="{% url 'userdashboard:u_Profile' %}">Go to home</a>
          <center><div class="fb-share-button" data-href="http://127.0.0.1:8000/" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share us with your friends</a></div>
        </center>
        </div>
      </div>
    </div>
  </div>
  
</div>


<script>
$(document).ready(function(){
  // Show the Modal on load
  $("#myModal").modal("show");
    
  // Hide the Modal
  $("#myBtn").click(function(){
    $("#myModal").modal("hide");
  });
});
</script>

{% endblock content %}

templates/donation/social.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
<p>SOMETHING</p>
      
{% for mess,pic in feed %}
  <div class="card" style="width: 18rem;">
    <img src="{{ pic }}" class="card-img-top" alt="...">
    <div class="card-body">
    <h5 class="card-title">Card titles</h5>
    <p class="card-text">{{ mess }}</p>
  </div>
</div>
{% endfor %}
</body>
</html>