oms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from homepage.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    path('homepage/',include('homepage.urls')),
    path('registration/',include('registration.urls')),
    path('orphanage_dashboard/', include('orphanageadmin.urls')),
    path('superuser/', include('superuser.urls')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('userdashboard/',include('userdashboard.urls')),
    path('donation/',include('donation.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') ,
            name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orphanageadmin/urls.py
from django.urls import path
from . import views
app_name = 'orphanageadmin'

urlpatterns = [
    path('RequestedDonations/',views.RequestedDonations,name='o_requesteddonations'),
    path('AcceptedDonations/',views.AcceptedDonations,name='o_accepteddonations'),
    path('ReceivedDonations/',views.ReceivedDonations,name='o_receiveddonations'),
    path('EmergencyRequest/',views.EmergencyRequest,name='o_emergencyrequest'),
    path('EmergencyCancel/',views.EmergencyCancel,name='o_emergencycancel'),
    path('EmergencyPostRemove/',views.EmergencyPostRemove,name='o_emergencypostremove'),
    path('HistoryOfPosts/',views.HistoryOfPosts,name='o_historyofposts'),
    path('RequestedDonationsAccRej/',views.RequestedDonationsAccRej,name='o_accrej'),
    path('AcceptedDonationsRecCan/',views.AcceptedDonationsRecCan,name='o_reccan'),
    path('JoinOrphan/',views.JoinOrphan,name='o_joinorphan'),
    path('Insertorphan/',views.Insertorphan,name='o_insertorphan'),
    path('Profile/',views.Profile,name='o_profile'),
    path('result/',views.result,name='o_result'),
    path('result1',views.result1,name='o_result1'),
    path('MoneyDonations/',views.MoneyDonations,name='o_moneydonations'),
    path('OrphanDetails/',views.OrphanDetails,name='o_orphandetails'),
    path('RequestedEvents/',views.RequestedEvents,name='o_requestedevents'),
    path('AcceptedEvents/',views.AcceptedEvents,name='o_acceptedevents'),
    path('PostEmergencyRequest/',views.PostEmergencyRequest,name='o_postemergencyrequest'),
    path('AcceptedEvents_ChangeStatus/',views.AcceptedEvents_ChangeStatus,name='o_acceptedeventschangestatus'),
    path('PostEmergencyRequest/',views.PostEmergencyRequest,name='o_postemergencyrequest'),
    path('OrphanDetailsDel/',views.OrphanDetailsDel,name='o_orphandetailsdel'),
    path('showevent/<int:id>',views.showevent,name='showevent'),
    path('deleteevent/<int:id>',views.deleteevent,name='deleteevent'),
    path('Requested_orphan',views.Requested_orphan,name='o_requestedorphan'),
    path('AccReq_orphan',views.AccReq_orphan,name='o_accreqorphan'),
    path('Accepted_orphan',views.Accepted_orphan,name='o_acceptedorphan'),
]

registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from registration.form import CustomAuthForm

app_name = 'registration'
urlpatterns = [
    path('', views.index, name='profile'),
    # path('donate_history', views.index1, name='donate_history'),
    # path('join_orphan', views.index2, name='join_orphan'),
    # path('near_you', views.index3, name='near_you'),
    # path('pending', views.index4, name='pending'),

    path('login', views.login_view, name='login'),
    path('register', views.signup, name='signup'),
    path(r'getData/<slug:user_type>/', views.get_data, name='get_data'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
         name='activate'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('logout/', views.logout_view, name= 'logout'),
    path('solution',views.solution,name='solution'),
    path('result',views.result,name='r_result1'),



    # path(r'password_reset/', auth_views.PasswordResetView.as_view() , name= 'password_reset'),
    # path(r'password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name= 'password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #
    # path(r'reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_engine='registration/password_reset_confirm.html'), name= 'password_reset_complete'),




    # path('register', views.orphanage_signup, name='orphanage_signup'),
    # path('login_result', views.loginstatus, name='loginstatus'),
    # path('login12', views.login12, name='login12'),
    # path('login1', views.login1, name='login1'),
    # path('signup1/user', views.user_signup1, name='user_signup1'),
    # path('signup12/user', views.user_signup12, name='user_signup12'),
    # path('signup1/orphanage', views.orphanage_signup1, name='orphanage_signup1'),
    # path('signup12/orphanage', views.orphanage_signup12, name='orphanage_signup12'),

]

orphanageadmin/models.py
from django.db import models

# Create your models here.

orphanageadmin/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from homepage.models import Orphan,Orphanage,donatevaluables,donatemoney,Emergency,Events,Orphan,AddOrphan,Transport
import datetime
import json


@login_required
def Profile(request):
    user = request.user
    print(user)
    qs = Orphanage.objects.get(orphanage_id = user)
    qs1=User.objects.get(username=user)
    #content = {'orphanage_name':orphanage.orphanage_name}
    print(qs.image,'###')
    return render(request,'orphanageadmin/profile.html',{"qs":qs,"qs1":qs1})

@login_required
def result1(request):
    user = request.user
    print(user)
    qs = Orphanage.objects.get(orphanage_id = user)
    qs1=User.objects.get(username=user)

    #content = {'orphanage_name':orphanage.orphanage_name}
    print(qs.orphanage_name)
    return render(request,'orphanageadmin/edit_profile.html',{"qs":qs,"qs1":qs1})

@login_required
def result(request):
    if request.method == 'POST':
        user = request.user
        print(user)
        empty=''
        qs = Orphanage.objects.get(orphanage_id = user)
        qs1=User.objects.get(username=user)

        orphanage_name=request.POST.get('orphanage_name')
        phone_no=request.POST.get('phone_no')
        year_of_establishment=request.POST.get('year_of_establishment')
        description=request.POST.get('description')
        address=request.POST.get('address')
        email=request.POST.get('email')
        print(orphanage_name)
        print(phone_no)
        print(year_of_establishment)
        print(description)
        print(address)

        
        if email==empty:
            pass
        else:
            qs1.email = email

        if phone_no==empty:
            pass
        else:
            qs.phone_no = phone_no

        if year_of_establishment == empty:
            pass
        else:
            qs.year_of_establishment = year_of_establishment
        if description == empty:
            pass
        else:
            qs.description = description

        if address == empty:
            pass
        else:
            qs.address = address



        qs1.save()
        qs.save()
        qs1=User.objects.get(username=user)
        qs = Orphanage.objects.get(orphanage_id=user)
        return render(request,'orphanageadmin/profile.html',{"qs":qs,"qs1":qs1})

@login_required
def RequestedDonations(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    donation_request = donatevaluables.objects.filter(orphanage_id = orphanage , status = 0)
    content = {'donation_request':donation_request}
    return render(request,'orphanageadmin/requested_donations.html',content)

@login_required
def RequestedDonationsAccRej(request):
    if request.method == 'POST':
        val = int(request.POST["val"])
        id1 = request.POST["id1"]
        donatevaluables.objects.filter( tid = id1).update(status = val)
        print(val)
        if val == 1:
            messages.success(request,'Successfully accepted the request')
            return redirect('orphanageadmin:o_requesteddonations')
        else:
            messages.warning(request,'Successfully rejected the request')
            return redirect('orphanageadmin:o_requesteddonations')

@login_required
def AcceptedDonations(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    donation_request = donatevaluables.objects.filter(orphanage_id = orphanage , status = 1)
    content = {'donation_request':donation_request}
    return render(request,'orphanageadmin/accepted_donations.html',content)

@login_required
def AcceptedDonationsRecCan(request):
    if request.method == 'POST':
        val = int(request.POST["val"])
        id1 = request.POST["id1"]
        donatevaluables.objects.filter( tid = id1).update(status = val)
        k=donatevaluables.objects.get( tid = id1,status=2)
        Transport.objects.filter(danation_id=k.pk,status=1).update(status=3)
        if val == 2:
            messages.success(request,'Successfully received the donation')
            return redirect('orphanageadmin:o_accepteddonations')
        else:
            messages.warning(request,'Successfully cancelled the donation')
            return redirect('orphanageadmin:o_accepteddonations')

@login_required
def ReceivedDonations(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    donation_request = donatevaluables.objects.filter(orphanage_id = orphanage , status = 2)
    content = {'donation_request':donation_request}
    return render(request,'orphanageadmin/received_donations.html',content)

@login_required
def MoneyDonations(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    donation_request = donatemoney.objects.filter(orphanage_id = orphanage,status=1)
    content = {'donation_request':donation_request}
    return render(request,'orphanageadmin/moneydonations.html',content)


@login_required
def RequestedEvents(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    donation_request = Events.objects.filter(orphanage_id = orphanage,status = 'Freshly Applied')
    content = {'donation_request':donation_request}
    return render(request,'orphanageadmin/requestedevents.html',content)

@login_required
def AcceptedEvents_ChangeStatus(request):
    if request.method == 'POST':
        val = int(request.POST["val"])
        id1 = request.POST["id1"]
        if val == 1:
            Events.objects.filter( id = id1).update(status = 'Accepted')
            messages.success(request,'Successfully accepted the request')
            return redirect('orphanageadmin:o_requestedevents')
        else:
            Events.objects.filter( id = id1).update(status = 'Rejected')
            messages.warning(request,'Successfully rejected the request')
            return redirect('orphanageadmin:o_requestedevents')

@login_required
def AcceptedEvents(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    a=Events.objects.filter(orphanage_id = orphanage,status = 'Accepted')
    l=[]
    for i in a:
        print(i.date_of_event)
        q=[None]*5
        g,h,j=str(i.date_of_event).split('-')
        q[0]=int(g)
        q[1]=int(h)
        q[2]=int(j)
        q[3]=i.event
        q[4]=i.pk
        print(i.date_of_event)
        l.append(q)
    b=json.dumps(l)
    return render(request,'orphanageadmin/acceptedevents.html',context={'t':b})

def showevent(request,id):
    a=Events.objects.get(pk=id)
    return render(request,'orphanageadmin/showevent.html',context={'t':a,'b':1})

def deleteevent(request,id):
    a=Events.objects.get(pk=id)
    a.delete()
    messages.warning(request,'Successfully Deleted the event')
    return render(request,'orphanageadmin/showevent.html',context={'b':0})


@login_required
def JoinOrphan(request):
    user = request.user
    return render(request,'orphanageadmin/joinorphan.html')

@login_required
def Insertorphan(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    if request.method == 'POST':
        date = str(datetime.datetime.now())
        date = date.split(' ')
        date1 = date[0].split('-')
        orphan_name = request.POST['name']
        date_of_birth = request.POST['date']
        gender = request.POST['gender']
        special_skills = request.POST['spskills']
        date2 = str(date_of_birth)
        date2 = date2.split('-')
        if int(date1[0]) < int(date2[0]) or (int(date1[0]) == int(date2[0]) and int(date1[1]) < int(date2[1])) or (int(date1[0]) == int(date2[0]) and int(date1[1]) == int(date2[1]) and int(date1[2]) < int(date2[2])):
            messages.warning(request,'Error in date, Fail to add')
            return redirect('orphanageadmin:o_joinorphan')
        else:
            p = Orphan.objects.create(orphanage_id=orphanage,orphan_name=orphan_name,date_of_birth=date_of_birth,gender=gender,special_skills=special_skills)
            p.save()
            messages.success(request,'Added orphan successfully')
            return redirect('orphanageadmin:o_joinorphan')

@login_required
def OrphanDetails(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    donation_request = Orphan.objects.filter(orphanage_id = orphanage)
    content = {'donation_request':donation_request}
    return render(request,'orphanageadmin/orphans.html',content)

@login_required
def OrphanDetailsDel(request):
    if request.method == 'POST':
        id1 = request.POST["id1"]
        Orphan.objects.filter(id = id1).delete()
    return redirect('orphanageadmin:o_orphandetails')


@login_required
def EmergencyRequest(request):
    user = request.user
    return render(request,'orphanageadmin/emergency_request.html')

def PostEmergencyRequest(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    if request.method == 'POST':
        problem = request.POST["problem"]
        requirement = request.POST["requirement"]
        p = Emergency(orphanage_id = orphanage, situation = problem , requirement = requirement,status=1)
        p.save()
        messages.success(request,'Successfully Posted')
        return redirect('orphanageadmin:o_emergencyrequest')

@login_required
def EmergencyCancel(request):
    user = request.user
    orphanage = Orphanage.objects.get(orphanage_id = user)
    donation_request = Emergency.objects.filter(orphanage_id = orphanage,status = 1)
    content = {'donation_request':donation_request}
    return render(request,'orphanageadmin/emergencycancel.html',content)

@login_required
def EmergencyPostRemove(request):
    if request.method == 'POST':
        id1 = request.POST["id1"]

templates/orphanageadmin/accepted_donations.html
{% extends 'orphanageadmin/basic.html' %}
{% load static %}
{% block content %}
<script>
    sidebar_shift("sidebar-donations")
</script>
        <center>
                <div>
                    {% if messages %}
                        {% for message in messages %}
                        <div class='alert alert-{{ message.tags }}'>
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
        </center>
        <br>
        <div class="content my-3">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover hoverable">
                                <div class="card-header ">
                                    <h4 class="card-title text-center"> Accepted Donations </h4>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-hover table-striped" >
                                        {% if  donation_request %}
                                        <thead><tr>
                                                    <th class='cnt'> User </th>
                                                    <th class='cnt'> Date </th>
                                                    <th class='cnt'> Type </th>
                                                    <th class='cnt'> Quantity </th>
                                                    <th class='cnt' colspan = '2' > Accept/Reject </th>
                                                </tr></thead>
                                                <tbody>
                                    {% for content in donation_request %}
                                    <tr>
                                            <td class= 'cnt'>{{ content.user_id }}</td>
                                            <td class= 'cnt'>{{ content.date_of_donation.date }}</td>
                                            {% if content.donation_type == 'C' %} 
                                                <td class= 'cnt'> Cloths </td>
                                                <td class= 'cnt'>{{ content.quantity }} </td>
                                            {% endif %}
                                            {% if content.donation_type == 'F' %} 
                                                <td class= 'cnt'> Food </td>
                                                <td class= 'cnt'>{{ content.quantity }} &nbsp; Kg</td>
                                            {% endif %}
                                            {% if content.donation_type == 'B' %} 
                                                <td class= 'cnt'> Book </td>
                                                <td class= 'cnt'>{{ content.quantity }} &nbsp; </td>
                                            {% endif %}
                                            {% if content.donation_type == 'E' %} 
                                                <td class= 'cnt'> Eletrical Appliances </td>
                                                <td class= 'cnt'>{{ content.quantity }} &nbsp; </td>
                                            {% endif %}
                                            {% if content.donation_type == 'O' %} 
                                                <td class= 'cnt'> Other </td>
                                                <td class= 'cnt'>{{ content.quantity }} &nbsp; </td>
                                            {% endif %}
                                            <td class='cnt' width="15%">
                                            <form method="post" action= "{% url 'orphanageadmin:o_reccan' %}" autocomplete="off" onsubmit="myButton.disabled = true; return true;">
                                                {% csrf_token %}
                                                <input type="hidden" name="id1" value={{ content.tid }}>
                                                <input type="hidden" name="val" value= 2 >
                                                <input class="acc btn" type="submit" value="Received" name ="myButton">
                                            </form>
                                            </td>
                                            <td class='cnt' width="15%">
                                            <form method="post" action= "{% url 'orphanageadmin:o_reccan' %}" autocomplete="off" onsubmit="myButton.disabled = true; return true;">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="id1" value={{ content.tid }}>
                                                    <input type="hidden" name="val" value= -2>
                                                    <input class="rej btn" type="submit" value="cancel" name ="myButton">
                                            </form>
                                        </td>
                                    </tr>    
                                {% endfor %}
                            </tbody>
                        {% else %}
                        <h5> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; No Accepted Donations Available </h5>
                        {% endif %}
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/orphanageadmin/acceptedevents.html
{% extends 'orphanageadmin/basic.html' %}
{% load static %}
{% block content %}
<script>
    sidebar_shift("sidebar-events")
</script>
<center>
                <div>
                    {% if messages %}
                        {% for message in messages %}
                        <div class='alert alert-{{ message.tags }}'>
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
            <br>
</center>
<!-- Start Here -->
        <h3 style="margin-left: 35%;"> Accepted Events </h3>
        <div id="caleandar" style="margin-left: 30%;mar ">

        </div>
        <script type="text/javascript">

        var f={{ t|safe }};
        console.log(f);
        var n=f.length;
        console.log(n);
        var i;

var events = [];
        for(i=0;i<n;i++)
        {
            console.log(f[i][0]);console.log(f[i][1]);console.log(f[i][2]);
            events[i]={'Date': new Date(Number(f[i][0]), Number(f[i][1])-1, f[i][2]), 'Title': 'View Details','Link':"{% url 'orphanageadmin:showevent' id=12345 %}".replace('12345', Number(f[i][4]))};
            console.log(events[i]['Date'])

        }
        var settings = {

Color: '',

LinkColor: '',

NavShow: true,

NavVertical: false,

NavLocation: '',

DateTimeShow: true,

DateTimeFormat: 'mmm, yyyy',

DatetimeLocation: '',

EventClick: '',

EventTargetWholeDay: false,

DisabledDays: [],

ModelChange: events

};
var element = document.getElementById('caleandar');

caleandar(element, events, settings);







        </script>
<!--End Here-->
{% endblock content %}

templates/orphanageadmin/basic.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title> Orphanage </title>
  <link rel="stylesheet" href="{% static 'orphanageadmin/theme2.css' %}">
        <script src="{% static 'orphanageadmin/caleandar.js' %}"></script>
        <script src="{% static 'orphanageadmin/admin-script.js' %}"></script>            
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
<link href="{% static 'orphanageadmin/admin-style.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'orphanageadmin/form.css' %}">


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'orphanageadmin/admin-script.js' %}"></script>
</head>

<body>
  <div class="container-fluid p-0 d-flex wrapper">
  
  <nav id="sidebar">

      <div class="sidebar-header p-3.5">
        <a href="#" class="mx-4">
              <img src="{% static 'homepage/img/logo.png' %}" class="nav-logo">
            </a>
    </div>

    <ul class="list-unstyled components">
        <li class="sidebar-profile">
            <a href="{% url 'orphanageadmin:o_profile' %}"><i class="fas fa-user mr-3"></i>Profile</a>
        </li>
        <li>
            <a href="#user-donate" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-donations"><i class="fas fa-donate mr-3"></i>Donations</a>
            <ul class="collapse list-unstyled" id="user-donate">
                <li>
                    <a href="{% url 'orphanageadmin:o_requesteddonations' %}" >Requested Donations</a>
                </li>
                <li>
                    <a href="{% url 'orphanageadmin:o_accepteddonations' %}">Accepted Donations</a>
                </li>
                <li>
                    <a href="{% url 'orphanageadmin:o_receiveddonations' %}">Received Donations</a>
                </li>
                <li>
                    <a href="{% url 'orphanageadmin:o_moneydonations' %}">Money Donations</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#Events" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-events"><i class="fas fa-hands-helping mr-3"></i>Events</a>
            <ul class="collapse list-unstyled" id="Events">
                <li>
                    <a href="{% url 'orphanageadmin:o_requestedevents' %}">Requested Events</a>
                </li>                        
                <li>
                    <a href="{% url 'orphanageadmin:o_acceptedevents' %}">Accepted Events</a>
                </li>
            </ul>
        </li>
        <li >
            <a href="#orphan" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-orphans"><i class="fas fa-user-friends mr-3"></i>Orphans</a>
            <ul class="collapse list-unstyled" id="orphan">
                <li>
                    <a href="{% url 'orphanageadmin:o_joinorphan' %}">Add Orphans</a>
                </li>                        
                <li>
                    <a href="{% url 'orphanageadmin:o_orphandetails' %}">Orphans</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#emergency" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-emergency"><i class="fas fa-bullhorn mr-3"></i>Emergency Post</a>
            <ul class="collapse list-unstyled" id="emergency">
                <li>
                    <a href="{% url 'orphanageadmin:o_emergencyrequest' %}">Post your request</a>
                </li>                        
                <li>
                    <a href="{% url 'orphanageadmin:o_emergencycancel' %}">Remove Emergency Posts</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#join_orphan" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-join"><i class="fas fa-hand-holding mr-3"></i>Join Orphan</a>
            <ul class="collapse list-unstyled" id="join_orphan">
                <li>
                    <a href="{% url 'orphanageadmin:o_requestedorphan' %}">Request</a>
                </li>                        
                <li>
                    <a href="{% url 'orphanageadmin:o_acceptedorphan' %}">Accepted</a>
                </li>
            </ul>
        </li>
    </ul>
</nav>	

<!-- side bar ends here -->
<!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light z-depth-0">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="c-navbar-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                
                <ul class="nav navbar-nav ml-auto">
                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-default"
                            aria-labelledby="navbarDropdownMenuLink-333">
                            <a class="dropdown-item" href="{% url 'orphanageadmin:o_profile' %}"><i class="fas fa-user mr-3"></i>Profile</a>
                            <hr class="m-0 p-0">
                            <a class="dropdown-item" href="{% url 'registration:logout' %}"><i class="fas fa-sign-out-alt mr-3"></i>Log Out</a>                            </div>
                    </li>
                </ul>
            </div>
        </nav>
      {% block content %}{% endblock content %}
    </div>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
</body>
</html>