oms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from homepage.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    path('homepage/',include('homepage.urls')),
    path('registration/',include('registration.urls')),
    path('orphanage_dashboard/', include('orphanageadmin.urls')),
    path('superuser/', include('superuser.urls')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('userdashboard/',include('userdashboard.urls')),
    path('donation/',include('donation.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') ,
            name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superuser/urls.py
from django.contrib import admin
from django.urls import path,include
from superuser import views
from django.conf import settings
from django.conf.urls.static import static

app_name='superuser'
urlpatterns = [
    path('freshlyapplied/', views.freshlyapplied,name='freshlyapplied'),
    path('accepted/', views.accepted,name='accepted'),
    path('rejected/', views.rejected,name='rejected'),
    path('check/', views.check,name='check'),
    path('addevent/',views.addevent,name='addevent'),
    path('checkdate/',views.checkdate,name='checkdate'),
    path('requestedevents/<int:pk>',views.requestedevents,name='requestedevents'),
    path('acceptedevents/',views.acceptedevents,name='acceptedevents'),
    path('rejectedevents/',views.rejectedevents,name='rejectedevents'),
    path('givereview/',views.givereview,name='givereview'),
   # path('showreview/',views.showreview,name='showreview'),


]

superuser/models.py
from django.db import models

# Create your models here.

superuser/views.py
from django.shortcuts import render, HttpResponse
from homepage.models import Orphanage,Events,review
import json
from django.http import JsonResponse
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth.decorators import login_required




def givereview(request):
    

    if request.method=='POST':
        print('jj')
        description=request.POST.get('description')
        rating=request.POST.get('ratingnew')
        review.objects.create(description=description,rating=rating,user=request.user)
        w=review.objects.all()
        for i in w:
            print(i.rating)
        return render(request,'superuser/showreview.html',context={'list':w})
    else:
        return render(request,'superuser/givereview.html')    




@login_required
def requestedevents(request,pk=0):
    if request.method=='POST':
        print('hii')
        user = request.user
        a=Events.objects.get(pk=pk)
        a.status='Cancelled By User'
        a.save()
        messages.warning(request,'Event got cancelled')
        a=Events.objects.filter(orphanage_id = orphanage,status = 'Freshly Applied')
        return render(request,'superuser/requestedevents.html',context={'t':a})
    else:
        user = request.user
        a=Events.objects.filter(user_id=user,status = 'Freshly Applied')
        return render(request,'superuser/requestedevents.html',context={'t':a})
@login_required
def acceptedevents(request):
    user = request.user
    a=Events.objects.filter(user_id=user,status = 'Accepted')
    return render(request,'superuser/acceptedevents.html',context={'t':a})

@login_required
def rejectedevents(request):
    user = request.user
    a=Events.objects.filter(user_id=user,status = 'Rejected')
    return render(request,'superuser/rejectedevents.html',context={'t':a})


def freshlyapplied(request):
    orphanages = Orphanage.objects.filter(status='Freshly Applied')

    t_dict = {'t': orphanages}
    return render(request, 'superuser/basic.html', context=t_dict)


def accepted(request):
    orphanages = Orphanage.objects.filter(status='Accepted')

    t_dict = {'t': orphanages}
    return render(request, 'superuser/basic.html', context=t_dict)


def rejected(request):
    orphanages = Orphanage.objects.filter(status='Rejected')

    t_dict = {'t': orphanages}
    return render(request, 'superuser/basic.html', context=t_dict)


def check(request):
    print('atlssld')
    if request.method == 'POST':
        a = request.POST.get('orphanage_name')
        print(a)
        if 'ACCEPT' in request.POST:
            print('camehere')
            z = Orphanage.objects.get(orphanage_name=a)
            z.status = 'Accepted'
            z.save()
            orphanages = Orphanage.objects.filter(status='Accepted')
            t_dict = {'t': orphanages}
            return render(request, 'superuser/basic.html', context=t_dict)
        if 'REJECT' in request.POST:
            print('camehere2')
            z = Orphanage.objects.get(orphanage_name=a)
            z.status = 'Rejected'
            z.save()
            orphanages = Orphanage.objects.filter(status='Rejected')
            t_dict = {'t': orphanages}
            return render(request, 'superuser/basic.html', context=t_dict)
def addevent(request):
    if request.method=='POST':
        print('cametoaddevent')
        date=request.POST.get('date')


        orphanage=request.POST.get('orphanage')
        print('orphanage='+str(orphanage))
        print('date='+str(date))
        event=request.POST.get('event')
        print(event)
        description=request.POST.get('description')
        print(description)
        orp=Orphanage.objects.get(orphanage_name=orphanage)
        Events.objects.create(user_id=request.user,orphanage_id=orp,date_of_event=date,event=event,description=description)
        '''subject='Confirmation of event'
        message='Your event is confirmed'
        from_mail='sudarshan333u@gmail.com'
        to_list=[str(request.user.email)]
        send_mail(subject,message,from_mail,to_list,fail_silently=True)'''
        messages.success(request,'Added Event successfully')
        return render(request,'superuser/addevent.html',context={'f':1})

    else:
        a=Orphanage.objects.all()
        l=[]
        for i in a:
            l.append(i.orphanage_name)
        b=l[0]
        return render(request,'superuser/addevent.html',context={'t':l[1:],'b':b,'f':0})
def checkdate(request):
    print('ghjk')
    response_data={}
    response_data['is_success']=True
    orphanage=Orphanage.objects.get(orphanage_name=request.GET.get('orphanage'))
    date=request.GET.get('date')
    print('date='+str(date))
    print('orphanage='+str(orphanage))

    a=Events.objects.filter(orphanage_id=orphanage)
    flag=0
    print('highgh')
    if a:
        print('highghjkl')
        for i in a:
            print('wenthere')
            print(i.date_of_event)
            print(date)
            if str(i.date_of_event)==str(date):
                flag=1
    print('theend')
    if flag==1:
        print('validbefore')
        response_data['valid']=False
        print('validafter')
    else:
        response_data['valid']=True
    print('atlast')
    return JsonResponse(response_data)

templates/superuser/acceptedevents.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-orphans")
</script>
            <!-- content starts here-->
            
            <div>
                {% if messages %}
                    {% for message in messages %}
                    <div class='alert alert-{{ message.tags }}'>
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="content my-3">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover hoverable">
                                <div class="card-header ">
                                    <h4 class="card-title text-center"> Accepted Events </h4>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-striped"  id = "customers">
                                        {% if  t %}
                                        <thead><tr>
                                            <th class='cnt'> Event </th>
                                            
                                            <th class='cnt'> Orphanage </th>
                                            <th class='cnt'> Date </th>
                                        </tr></thead>
                                        <tbody>
                                        {% for i in t %}
                                        <tr>
                                            <td class= 'cnt'>{{ i.event }}</td>
                                            <td class= 'cnt'>{{ i.orphanage_id.orphanage_name }}</td>
                                            <td class= 'cnt'>{{ i.date_of_event }}</td>
                                            
                                            
                                            
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    {% else %}
                                    <h5> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; No Accepted Events Available </h5>
                                    {% endif %}
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
                        <!-- content ends here-->
{% endblock content %}

templates/superuser/addevent.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-orphans")
</script>
            <!-- content starts here-->
            {% if f == 1 %}
            <div>
                {% if messages %}
                    {% for message in messages %}
                    <div class='alert alert-{{ message.tags }}'>
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            {% else %}
            <br>
            <div class="content my-3">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="text-center text-heading title">Add Event</h5>
                            </div>
                            <div class="card-body px-5">
                                <div class="container">
                                <form class="from-horizontal" method="post" action="{%  url 'superuser:addevent' %}" autocomplete="off" onsubmit="myButton.disabled = true;">
                                        {% csrf_token %}
                                    <!-- Name -->
                                    <center><span id="datecheck" ></span></center>

                                    <div class="md-form mt-3 ">
                                            <label for="orphanage">Orphanage</label>
                                            <br>
                                            <br>

                                            <select style="margin-left: 0%" class="btn btn-outline-info dropdown-toggle z-depth-0 border-bottom drop-btn" name="orphanage" id="orphanage">
                                                    <option value="{{ b }}" selected>{{ b }}</option>
                                                    {% for orphanages in t %}
                                                    <option value="{{ orphanages }}">{{ orphanages }}</option>
                                                    {% endfor %}
                                            </select>
                                    </div>
                                    <!-- date picker -->
                                    <br>
                                    <div class="md-form">
                                        <input type="date" id="date" class="form-control" onchange="see(this.id)" name="date" required>
                                        <label for="date"> Date of Event</label>
                                    </div>
                                    <div class="md-form mt-3 ">
                                            <input type="text" name = "event" id = "event" class="form-control"  maxlength='30' required>
                                            <label for="event"> Event </label>
                                        </div>
                                <!-- inline radio buttons -->

                                    <!-- Name -->
                                    <div class="md-form mt-3 ">
                                        <input type="text" name = "description" id = "description" class="form-control"  maxlength='50' required>
                                        <label for="description"> Description </label>
                                    </div>
                                    <div id='error'></div>

                                    <div class="md-form">
                                        <button type="submit" class="btn btn-primary waves-effect waves-light form-button" id="submitbutton">Submit</button>
                                    </div>
                                </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            <!-- SCRIPTS -->

<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
<script type="text/javascript" src="{% static 'superuser/js/admin-script.js' %}"></script>
<script type="text/javascript">



    function see(element) {
        var date = document.getElementById(element).value;
        var orphanage = document.getElementById('orphanage').value;
        console.log(date)
        console.log(orphanage)


        $.ajax({


            url: "{% url 'superuser:checkdate' %}",
            data: {
                date:date,
                orphanage:orphanage,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            method: 'GET',
            dataType:"json",

            success: function (data) {
                console.log('hiitojson');
                console.log(data);
                if (data.is_success==true){
                  if (data.valid==false){
                    console.log('cametoerror')
                    alert('Date not available')
                    document.getElementById('datecheck').innerText='Date not available'
                    $('#datecheck').css("color","red");

                    $('#submitbutton').attr("disabled", true);
                    document.getElementById('error').innerText='Please satisfy all the conditions';
                    $('#error').css("color","red");



                  }
                  else{
                    document.getElementById('datecheck').innerText='Date available'
                    $('#datecheck').css("color","green");
                    $('#submitbutton').attr("disabled",false);
                    document.getElementById('error').innerText=''


                  }
                }
            }
        });
    }

    </script>


                        <!-- content ends here-->
{% endblock content %}

templates/superuser/basic.html
<html>
<head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">


</head> 
<body>
    <a href="{% url 'superuser:freshlyapplied' %}" class="btn btn-outline-primary"   style="margin-left: 30px;margin-top: 30px">Freshly Applied</a>
    <a href="{% url 'superuser:accepted' %}" class="btn btn-outline-primary"   style="margin-left: 30px;;margin-top: 30px">Accepted</a>
    <a href="{% url 'superuser:rejected' %}" class="btn btn-outline-primary"   style="margin-left: 30px;;margin-top: 30px">Rejected</a>
    {% if t %}
    <h4 style="margin-left: 30px;margin-top:30px">List Of Orphanages</h4>
    

    {% for orphanage in t %}
    <form action="{% url 'superuser:check' %}"  method="POST">
            {% csrf_token %}
    
        <div class="card" style="width: 80rem;margin-left: 30px">
                <div class="card-body">
                    
                  <input type="text"  name="orphanage_name" value="{{ orphanage.orphanage_name }}" style="border:none;font-weight: bold" readonly>
                  
                  <p class="card-text">{{orphanage.description}}</p>
                  <h6>Year of establishment: {{orphanage.year_of_establishment}}</h6>
                  <h6>Address: {{orphanage.address}}</h6>
                  <h6>Phone Number: {{orphanage.phone_no}}</h6>
                  <h6>Status: {{orphanage.status}}</h6>


                  {% if orphanage.status == "Freshly Applied" %}
                    <button type="submit" class="btn btn-primary" name="ACCEPT" value="ACEEPT">ACCEPT</button>
                    <button type="submit" class="btn btn-primary" name="REJECT" value="REJECT">REJECT</button>
                  {% endif %}
                    
                  {% if orphanage.status == "Accepted" %}
                  <button type="submit" class="btn btn-primary" name="REJECT">REJECT</button>

                  {% endif %}
                </div>
              </div>
    </form>          
    {% endfor %}
    {% else %}


    <p><h1>No Orphanages to show</h1></p>       
    {% endif %}   
    
    
</body>       
</html>

templates/superuser/givereview.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
        <link rel="stylesheet" type="text/css" href="{% static 'superuser/css/givereview.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body>
    <h1 class='hii'>hii</h1>
        <form method="POST" action='{% url "superuser:givereview" %}'>
        {% csrf_token %}

        <textarea rows="4" cols="50" name="description">
        </textarea>        
        <br>
        <div class="star-rating">
                <input id="star-5" type="radio" name="ratingnew" value="5">
                <label for="star-5" title="5 stars">
                        <i class="active fa fa-star" aria-hidden="true"></i>
                </label>
                <input id="star-4" type="radio" name="ratingnew" value="4">
                <label for="star-4" title="4 stars">
                        <i class="active fa fa-star" aria-hidden="true"></i>
                </label>
                <input id="star-3" type="radio" name="ratingnew" value="3">
                <label for="star-3" title="3 stars">
                        <i class="active fa fa-star" aria-hidden="true"></i>
                </label>
                <input id="star-2" type="radio" name="ratingnew" value="2">
                <label for="star-2" title="2 stars">
                        <i class="active fa fa-star" aria-hidden="true"></i>
                </label>
                <input id="star-1" type="radio" name="ratingnew" value="1">
                <label for="star-1" title="1 star">
                        <i class="active fa fa-star" aria-hidden="true"></i>
  
                </label>
        </div>
        <br>
        <button type="submit">Submit</button>
        </form>              
</body>
</html>

templates/superuser/rejectedevents.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-orphans")
</script>
            <!-- content starts here-->
            
            <div>
                {% if messages %}
                    {% for message in messages %}
                    <div class='alert alert-{{ message.tags }}'>
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="content my-3">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover hoverable">
                                <div class="card-header ">
                                    <h4 class="card-title text-center"> Rejected Events </h4>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-striped"  id = "customers">
                                        {% if  t %}
                                        <thead><tr>
                                            <th class='cnt'> Event </th>
                                            
                                            <th class='cnt'> Orphanage </th>
                                            <th class='cnt'> Date </th>
                                        </tr></thead>
                                        <tbody>
                                        {% for i in t %}
                                        <tr>
                                            <td class= 'cnt'>{{ i.event }}</td>
                                            <td class= 'cnt'>{{ i.orphanage_id.orphanage_name }}</td>
                                            <td class= 'cnt'>{{ i.date_of_event }}</td>
                                            
                                            
                                            
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    {% else %}
                                    <h5> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; No Rejected Events Available </h5>
                                    {% endif %}
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
                        <!-- content ends here-->
{% endblock content %}

templates/superuser/requestedevents.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-orphans")
</script>
            <!-- content starts here-->
            
            <div>
                {% if messages %}
                    {% for message in messages %}
                    <div class='alert alert-{{ message.tags }}'>
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="content my-3">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover hoverable">
                                <div class="card-header ">
                                    <h4 class="card-title text-center"> Requested Events </h4>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-striped"  id = "customers">
                                        {% if  t %}
                                        <thead><tr>
                                            <th class='cnt'> Event </th>
                                            
                                            <th class='cnt'> Orphanage </th>
                                            <th class='cnt'> Date </th>
                                            <th class='cnt' colspan = '2' > CANCELLATION </th>
                                        </tr></thead>
                                        <tbody>
                                        {% for i in t %}
                                        <tr>
                                            <td class= 'cnt'>{{ i.event }}</td>
                                            <td class= 'cnt'>{{ i.orphanage_id.orphanage_name }}</td>
                                            <td class= 'cnt'>{{ i.date_of_event }}</td>
                                            
                                            <td  class='cnt' >
                                            <form method="post" action= "{% url 'superuser:requestedevents' i.pk  %}" >
                                                {% csrf_token %}
                                                
                                                
                                                <input class="rej btn" type="submit" value="CANCEL EVENT" >
                                            </form>
                                            </td>
                                            
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    {% else %}
                                    <h5> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; No Requested Events Available </h5>
                                    {% endif %}
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
                        <!-- content ends here-->
{% endblock content %}

templates/superuser/showreview.html
{% load static %}
<html lang="en">

<head>
        <link rel="stylesheet" type="text/css" href="{% static 'superuser/css/givereview.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>



</head>
<body>
{% for review in list %}

                    <p>{{ review.description }}</p>
                <div class="star-rating">
                    <input id="star-5_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}" value="5" checked disabled>
                    <label for="star-5_{{ review.pk }}" title="5 stars">
  					    <i class="active fa fa-star" aria-hidden="true"></i>
                    </label>

                    <input id="star-4_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}" value="5" checked disabled>
                    <label for="star-4_{{ review.pk }}" title="5 stars">
  					    <i class="active fa fa-star" aria-hidden="true"></i>
                    </label>
                    <input id="star-3_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}" value="5" checked disabled>
                    <label for="star-3_{{ review.pk }}" title="5 stars">
  					    <i class="active fa fa-star" aria-hidden="true"></i>
                    </label>
                    <input id="star-2_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}" value="5" checked disabled>
                    <label for="star-2_{{ review.pk }}" title="5 stars">
  					    <i class="active fa fa-star" aria-hidden="true"></i>
                    </label>
                    <input id="star-1_{{ review.pk }}" type="radio" name="ratingnew_{{ review.pk }}" value="5" checked disabled>
                    <label for="star-1_{{ review.pk }}" title="5 stars">
  					    <i class="active fa fa-star" aria-hidden="true"></i>
                    </label>
                    <script>
                        console.log($('input[name="ratingnew_{{ review.pk }}"]:radio'));
                        $($('input[name="ratingnew_{{ review.pk }}"]:radio')[5-{{ review.rating }}])
                            .prop("checked", true);
                    </script>
{% endfor %}                    
                    
</div>
</body>
</html>                    