donation/urls.py
from django.urls import path, include
from donation import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('money',views.testdonatemoney)
router.register('user', views.CurrentUserViewSet)
router.register('orphanage',views.testorphanage)


app_name = 'donation'

urlpatterns = [
    path('test/',include(router.urls)),
    path('api/',views.rest_moneyview,name='rest'),
    path('donate_money/',views.donatemoneyview,name='donatemoney'),
    path('donate_valuables/',views.donatevaluablesview,name='donate_valuables'),
    path('donation_done/',views.donation_completedview,name='completed'),
    path('donation_interrupt/',views.donation_interruptview,name='cancel'),
    path('requestplaced/',views.donation_completedview,name='request_placed'),
    path('paypal_home/<int:tid>/<int:amount>/<str:orphanage_id1>/',views.paypal_home,name='inprogress'),
    path('paypal_return/',views.paypal_return),
    path('paypal_cancel/',views.paypal_cancel),
#    path('facebook/',views.facebookview,name='facebook'),
    path('social/',views.socialview,name='social'),
    path('Accepted/',views.acceptedview,name='accepted'),
    path('Rejected/',views.rejectedview,name='rejected'),
    path('history/',views.historyview,name='history'),
    path('received/',views.receivedview,name='received'),

]

oms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from homepage.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    path('homepage/',include('homepage.urls')),
    path('registration/',include('registration.urls')),
    path('orphanage_dashboard/', include('orphanageadmin.urls')),
    path('superuser/', include('superuser.urls')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('userdashboard/',include('userdashboard.urls')),
    path('donation/',include('donation.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') ,
            name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from registration.form import CustomAuthForm

app_name = 'registration'
urlpatterns = [
    path('', views.index, name='profile'),
    # path('donate_history', views.index1, name='donate_history'),
    # path('join_orphan', views.index2, name='join_orphan'),
    # path('near_you', views.index3, name='near_you'),
    # path('pending', views.index4, name='pending'),

    path('login', views.login_view, name='login'),
    path('register', views.signup, name='signup'),
    path(r'getData/<slug:user_type>/', views.get_data, name='get_data'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
         name='activate'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('logout/', views.logout_view, name= 'logout'),
    path('solution',views.solution,name='solution'),
    path('result',views.result,name='r_result1'),



    # path(r'password_reset/', auth_views.PasswordResetView.as_view() , name= 'password_reset'),
    # path(r'password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name= 'password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #
    # path(r'reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_engine='registration/password_reset_confirm.html'), name= 'password_reset_complete'),




    # path('register', views.orphanage_signup, name='orphanage_signup'),
    # path('login_result', views.loginstatus, name='loginstatus'),
    # path('login12', views.login12, name='login12'),
    # path('login1', views.login1, name='login1'),
    # path('signup1/user', views.user_signup1, name='user_signup1'),
    # path('signup12/user', views.user_signup12, name='user_signup12'),
    # path('signup1/orphanage', views.orphanage_signup1, name='orphanage_signup1'),
    # path('signup12/orphanage', views.orphanage_signup12, name='orphanage_signup12'),

]

superuser/urls.py
from django.contrib import admin
from django.urls import path,include
from superuser import views
from django.conf import settings
from django.conf.urls.static import static

app_name='superuser'
urlpatterns = [
    path('freshlyapplied/', views.freshlyapplied,name='freshlyapplied'),
    path('accepted/', views.accepted,name='accepted'),
    path('rejected/', views.rejected,name='rejected'),
    path('check/', views.check,name='check'),
    path('addevent/',views.addevent,name='addevent'),
    path('checkdate/',views.checkdate,name='checkdate'),
    path('requestedevents/<int:pk>',views.requestedevents,name='requestedevents'),
    path('acceptedevents/',views.acceptedevents,name='acceptedevents'),
    path('rejectedevents/',views.rejectedevents,name='rejectedevents'),
    path('givereview/',views.givereview,name='givereview'),
   # path('showreview/',views.showreview,name='showreview'),


]

userdashboard/urls.py
from django.urls import path
from . import views
app_name = 'userdashboard'

urlpatterns = [
path('Profile',views.Profile,name='u_Profile'),
path('result1',views.profileupdate,name='u_result11'),
path('result12', views.editprofile, name='u_result12'),
path('requestJoinOrphan', views.requestJoinOrphan, name = "request_joinorphan"),
path('acceptedJoinOrphanReqs', views.acceptedJoinOrphan_requests, name= "accepted_joinorphan"),
path('rejectedJoinOrphanReqs', views.rejectedJoinOrphan_requests, name= "rejected_joinorphan"),
path('pendingJoinOrphanReqs', views.pendingJoinOrphan_requests, name= "pending_joinorphan")
]

userdashboard/models.py
from django.db import models

# Create your models here.

userdashboard/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from homepage.models import Orphan,Orphanage,donatevaluables,donatemoney,Emergency,Events,Orphan,UserDetails,AddOrphan

@login_required
def Profile(request):
    user = request.user
    print(user)
    qs = User.objects.get(username=user)
    qs1=UserDetails.objects.get(user_id=qs)
    #content = {'orphanage_name':orphanage.orphanage_name}
    #print(qs.first_name,qs.last_name,qs.email)
    return render(request,'userdashboard/profile.html',{"qs":qs,"qs1":qs1})

@login_required
def profileupdate(request):
    user = request.user
    print(user)
    qs = User.objects.get(username=user)
    qs1=UserDetails.objects.get(user_id=qs)
    #content = {'orphanage_name':orphanage.orphanage_name}
    #print(qs.first_name,qs.last_name,qs.email)
    return render(request,'userdashboard/edit_profile.html',{"qs":qs,"qs1":qs1})

@login_required
def editprofile(request):
    if request.method == 'POST':
        user = request.user
        print(user)
        empty=''
        first_name=request.POST['firstname']
        last_name=request.POST['lastname']
        phone_no=request.POST['phone_no']
        email=request.POST['email']
        #address=request.POST['address']
        qs = User.objects.get(username=user)
        qs1 = UserDetails.objects.get(user_id=qs)
        if first_name ==empty:
            pass
        else:
            qs.first_name=first_name

        if last_name ==empty:
            pass
        else:
            qs.last_name=last_name

        if phone_no ==empty:
            pass
        else:
            qs1.phone_no=phone_no
        if email ==empty:
            pass
        else:
            qs.email=email
        qs.save()
        qs1.save()
        qs = User.objects.get(username=user)
        qs1 = UserDetails.objects.get(user_id=qs)
        # content = {'orphanage_name':orphanage.orphanage_name}
        # print(qs.first_name,qs.last_name,qs.email)
        return render(request, 'userdashboard/profile.html', {"qs": qs, "qs1": qs1})

def requestJoinOrphan(request):
    if request.method == "POST":
        print('orp=')
        print(request.POST['orphanage'])
        joinorphan_request = AddOrphan.objects.create(
         user_id=request.user,
         orphanage_id= Orphanage.objects.get(orphanage_name=request.POST['orphanage']),
         name=request.POST['name'],
         gender=request.POST['gender'],
         find_place=request.POST['find_place'],
         ref_no=0,
         date_of_birth=request.POST['DOB']
        )
        joinorphan_request.save()
        all_orphanages = Orphanage.objects.all()
        all_orphanages_list = []
        for item in all_orphanages:
            print(item.orphanage_name)
            all_orphanages_list.append(item.orphanage_name)
        messages.success(request, 'Your request to join an orphan has been sent, it will be verified soon.')
        return render(request, 'userdashboard/request_joinorphan.html',
                      {'orphanages': all_orphanages_list})
    else:
        all_orphanages = Orphanage.objects.all()
        all_orphanages_list = []
        for item in all_orphanages:
            all_orphanages_list.append(item.orphanage_name)
        return render(request, 'userdashboard/request_joinorphan.html', {'orphanages': all_orphanages_list})

def acceptedJoinOrphan_requests(request):
    accepted_joinorphan_requests = AddOrphan.objects.filter(ref_no=1, user_id=request.user)
    return render(request, 'userdashboard/accepted_joinorphan_request.html',{'accepted_requests': accepted_joinorphan_requests})

def rejectedJoinOrphan_requests(request):
    rejected_joinorphan_requests = AddOrphan.objects.filter(ref_no=-1, user_id=request.user)
    return render(request, 'userdashboard/rejected_joinorphan_request.html', {'rejected_requests': rejected_joinorphan_requests})

def pendingJoinOrphan_requests(request):
    pending_joinorphan_requests = AddOrphan.objects.filter(ref_no=0, user_id=request.user)
    return render(request, 'userdashboard/pending_joinorphan_request.html',
                  {'pending_requests': pending_joinorphan_requests})

templates/userdashboard/accepted_joinorphan_request.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-joinorphan")
</script>
    <!-- content starts here-->
    <div>
        {% if messages %}
            {% for message in messages %}
            <div class='alert alert-{{ message.tags }}'>
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="content my-3">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card strpied-tabled-with-hover hoverable">
                        <div class="card-header">
                            <h5 class="text-center text-heading title">Accepted join orphan request</h5>
                        </div>
                        <div class="card-body table-full-width table-responsive">
                            <table class="table table-hover table-striped" >
                                {% if accepted_requests %}
                                <thead><tr>
                                    <th  class= 'cnt'> Name </th>
                                    <th  class= 'cnt'> Date of Birth </th>
                                    <th  class= 'cnt'> Gender </th>
                                    <th  class= 'cnt'> Find place </th>
                                    <th  class= 'cnt'> Requested orphanage </th>
                                </tr></thead>
                                {% for accepted_request in accepted_requests %}
                                <tr>
                                    <td class= 'cnt'>{{ accepted_request.name }}</td>
                                    <td class= 'cnt'>{{ accepted_request.date_of_birth }}</td>
                                    <td class= 'cnt'>{{ accepted_request.gender }}</td>
                                    <td class= 'cnt'>{{ accepted_request.find_place }}</td>
                                    <td class= 'cnt'>{{ accepted_request.orphanage_id.orphanage_name }}</td>

                                </tr>
                            {% endfor %}
                            </tbody>
                        {% else %}
                        <h5> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; No accepted requests yet </h5>
                        {% endif %}
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- content ends here-->
{% endblock content %}

templates/userdashboard/basic.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title> Orphanage </title>
  <link rel="stylesheet" href="{% static 'orphanageadmin/theme2.css' %}">
        <script src="{% static 'orphanageadmin/caleandar.js' %}"></script>
        <script src="{% static 'orphanageadmin/admin-script.js' %}"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
<link href="{% static 'orphanageadmin/admin-style.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'orphanageadmin/form.css' %}">


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'orphanageadmin/admin-script.js' %}"></script>
</head>

<body>
  <div class="container-fluid p-0 d-flex wrapper">

  <nav id="sidebar">
    <div class="sidebar-header p-3.5">
        <a href="#" class="mx-4">
              <img src="{% static 'homepage/img/logo.png' %}" class="nav-logo">
            </a>
    </div>
    <ul class="list-unstyled components">
        <li class="sidebar-profile">
            <a href="{% url 'userdashboard:u_Profile' %}"><i class="fas fa-user mr-3"></i>Profile</a>
        </li>
        <li >
            <a href="#donations" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-donate"><i class="fas fa-donate mr-3"></i>Money Donations</a>
            <ul class="collapse list-unstyled" id="donations">
                <li>
                    <a href="{% url 'donation:donatemoney' %}">Donate</a>
                </li>
                <li>
                    <a href="{% url 'donation:history' %}">History</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#Valuable" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-valuable"><i class="fas fa-hamburger mr-3"></i>Valuable Donations</a>
            <ul class="collapse list-unstyled" id="Valuable">
                <li>
                    <a href="{% url 'donation:donate_valuables' %}">Donate</a>
                </li>
                <li>
                    <a href="{% url 'donation:accepted' %}">Accepted Donations</a>
                </li>
                <li>
                    <a href="{% url 'donation:rejected' %}">Rejected Donations</a>
                </li>
                <li>
                    <a href="{% url 'donation:received' %}">Not yet reviewed</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#Events" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-events"><i class="fas fa-hands-helping mr-3"></i>Events</a>
            <ul class="collapse list-unstyled" id="Events">

                <li>
                    <a href="{% url 'superuser:addevent' %}">Add an event</a>
                </li>
                <li>
<a href="{% url 'superuser:requestedevents' pk=0 %}">Requested Events</a>
</li>
<li>
<a href="{% url 'superuser:acceptedevents' %}">Accepted Events</a>
</li>
<li>
<a href="{% url 'superuser:rejectedevents' %}">Rejected Events</a>
</li>
</ul>
</li>

        <li>
{#            <a href="#"><i class="fas fa-hand-holding mr-3"></i>Join Orphan</a>#}
            <a href="#joinorphan_toggle" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-joinorphan"><i class="fas fa-hand-holding mr-3"></i>Join Orphan</a>
            <ul class="collapse list-unstyled" id="joinorphan_toggle">
                <li>
                    <a href="{% url 'userdashboard:request_joinorphan' %}">Request</a>
                </li>
                <li>
                    <a href="{% url 'userdashboard:accepted_joinorphan' %}">Accepted</a>
                </li>
                <li>
                    <a href="{% url 'userdashboard:rejected_joinorphan' %}">Rejected</a>
                </li>
                <li>
                    <a href="{% url 'userdashboard:pending_joinorphan' %}">Pending</a>
                </li>
            </ul>
        </li>
        <li class="sidebar-about orphan">
            <a href="#"><i class="far fa-thumbs-up mr-3"></i>About Orphanages</a>
        </li>
    </ul>
</nav>

<!-- side bar ends here -->
<!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light z-depth-0">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="c-navbar-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>

                <ul class="nav navbar-nav ml-auto">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-default"
                            aria-labelledby="navbarDropdownMenuLink-333">
                            <a class="dropdown-item" href="{% url 'userdashboard:u_Profile' %}"><i class="fas fa-user mr-3"></i>Profile</a>
                            <hr class="m-0 p-0">
                            <a class="dropdown-item" href="{% url 'registration:logout' %}"><i class="fas fa-sign-out-alt mr-3"></i>Log Out</a>                            </div>
                    </li>
                </ul>
            </div>
        </nav>
      {% block content %}{% endblock content %}
    </div>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
</body>
</html>

templates/userdashboard/edit_profile.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-profile")
</script>
        <br>
            <!-- content starts here-->

            <div class="content my-3">
                <div class="row">
                    <div class="col">
                            <div class="card">
                                    <div class="card-header">
                                      <h5 class="title">Edit Profile</h5>
                                    </div>
                                    <div class="card-body">
                                      <form action="{% url 'userdashboard:u_result12' %}" method="post">{% csrf_token %}
                                        <div class="row">
                                          <div class="col-md-5 pr-1">
                                            <div class="form-group">
                                              <label>Username (disabled)</label>
                                              <input type="text" class="form-control" disabled="" placeholder="Company" value="{{ qs.username }}" name="username" >
                                            </div>
                                          </div>
                                          <div class="col-md-3 px-1">
                                            <div class="form-group">
                                              <label>First name</label>
                                              <input type="text" class="form-control" placeholder="firstname" value="{{ qs.first_name }}" name="firstname">
                                            </div>
                                          </div>
                                          <div class="col-md-4 pl-1">
                                            <div class="form-group">
                                              <label >Last name</label>
                                              <input type="text" class="form-control" placeholder="lastname" value="{{ qs.last_name}}" name="lastname">
                                            </div>
                                          </div>
                                        </div>
                                        <div class="row">
                                          <div class="col-md-6 pr-1">
                                            <div class="form-group">
                                              <label>Phone Number</label>
                                              <input type="text" class="form-control" placeholder="Phone Number" value="{{ qs1.phone_no}}" name="phone_no">
                                            </div>
                                          </div>
                                          <div class="col-md-6 pl-1">
                                            <div class="form-group">
                                              <label for="exampleInputEmail1">Email address</label>
                                              <input type="email" class="form-control" placeholder="Email" value="{{ qs.email }}" name="email">
                                            </div>
                                          </div>
                                        </div>
                                        <div class="row">
                                          <div class="col-md-12">
                                            <div class="form-group">
                                              <label>Address</label>
                                              <input type="text" class="form-control" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09">
                                            </div>
                                          </div>
                                        </div>
                                        <div class="row">
                                          <div class="col-md-4 pr-1">
                                            <div class="form-group">
                                              <label>City</label>
                                              <input type="text" class="form-control" placeholder="City" value="Mike">
                                            </div>
                                          </div>
                                          <div class="col-md-4 px-1">
                                            <div class="form-group">
                                              <label>Country</label>
                                              <input type="text" class="form-control" placeholder="Country" value="Andrew">
                                            </div>
                                          </div>
                                          <div class="col-md-4 pl-1">
                                            <div class="form-group">
                                              <label>Postal Code</label>
                                              <input type="number" class="form-control" placeholder="ZIP Code">
                                            </div>
                                          </div>
                                        </div>
                                        <!--<div class="row">
                                          <div class="col-md-12">
                                            <div class="form-group">
                                              <label>About Me</label>
                                              <textarea rows="4" cols="80" class="form-control" placeholder="Here can be your description" value="Mike">Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.</textarea>
                                            </div>
                                          </div>
                                        </div>-->
                                        <div class="text-center">
                                        <button class="btn btn-primary"  >Save </button>
                                      </div>
                                      </form>

                                    </div>
                                  </div>
                    </div>
                </div>
            </div>


            <!-- content ends here-->
{% endblock content %}

templates/userdashboard/profile.html
{% extends 'userdashboard/basic.html' %}
{% load static %}
{% block content %}
<script>
        sidebar_shift("sidebar-profile")
</script>
        <br>
            <!-- content starts here-->
            <div class="content my-3">
                <div class="row">
                    <div class="col">
                            <div class="card">
                                    <div class="card-header">
                                      <h5 class="title">Profile</h5>
                                    </div>
                                    <div class="card-body">
                                      <div class="row">
                                        <div class="col col-4 pt-4">
                                          <img src="{% static 'homepage/img/photo.jpg' %}" class="profile-img">
                                        </div>
                                        <div class="col col-6">
                                          <div class="row my-2">
                                            <div class="col ">Name</div>
                                            <div class="col">:</div>
                                            <div class="col ">{{ qs.username }}</div>
                                          </div>
                                          <div class="row my-5">
                                            <div class="col">phone number</div>
                                            <div class="col">:</div>
                                            <div class="col">{{ qs1.phone_no }}</div>
                                          </div>
                                          <div class="row my-5">
                                            <div class="col">firstname</div>
                                            <div class="col">:</div>
                                            <div class="col">{{ qs.first_name}}</div>
                                          </div>
                                          <div class="row my-5">
                                            <div class="col">lastname</div>
                                            <div class="col">:</div>
                                            <div class="col">{{ qs.last_name }}</div>
                                          </div>
                                          <div class="row my-5">
                                            <div class="col col-4">Email</div>
                                            <div class="col">:</div>
                                            <div class="col">{{ qs.email}}</div>
                                          </div>
                                          <div class="row my-5">
                                            <div class="col">Gender</div>
                                            <div class="col">:</div>
                                            <div class="col">{{ qs1.gender}}</div>
                                          </div>
                                        </div>
                                    </div>

                                  <form action="{%url 'userdashboard:u_result11' %}" method="post" class="text-center">
                                    {% csrf_token %}

                                  <button class="btn btn-primary "  >Edit Profile</button>

                                  </form>
                                    </div>

                                  </div>

                    </div>
                </div>
            </div>
            <!-- content ends here-->
{% endblock content %}